# For mysql2
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306

development:
  <<: *default
  database: development
  username: root
  password: root
test:
  <<: *default
  database: test
  username: root
  password: root

production:
  <<: *default
  databse: production
  username: root
  password: root
